const Items = [
  {
    id: 0,
    new: true,
    tag: 'toys',
    name: '나무 요정',
    price: '30,000',
    link: 'treefairy.png',
    description: '나무로 만든 요정 (5개 1세트)',
  },
  {
    id: 1,
    new: true,
    tag: 'others',
    name: '소꿉놀이용 뜨개 장갑',
    price: '10,000',
    link: 'wintergloves.png',
    description: '털실 손뜨게 놀이용 주방 장갑 15㎝*10.5㎝ (가로*세로)',
  },
  {
    id: 2,
    new: true,
    tag: 'others',
    name: '마크라메 벽걸이',
    price: '6,000',
    link: 'wallcloth.png',
    description: '마크라메로 만든 벽걸이',
  },
  {
    id: 3,
    new: true,
    tag: 'others',
    name: '편백나무 큐브 베개',
    price: '12,000',
    link: 'pillow.jpeg',
    description: '7*7*7mm 크기의 편백 알갱이를 담은 망사주머니 베개',
  },
  {
    id: 4,
    new: false,
    tag: 'toys',
    name: '도토리집 인형',
    price: '20,000',
    link: 'acornDoll.png',
    description: '7*7*7mm 크기의 편백 알갱이를 담은 망사주머니 베개',
  },
  {
    id: 5,
    new: false,
    tag: 'toys',
    name: '오재미',
    price: '2,000',
    link: 'ojemi.png',
    description: '면과 매실씨앗으로 만든 오재미',
  },
  {
    id: 6,
    new: false,
    tag: 'toys',
    name: '버섯요정집',
    price: '180,000',
    link: 'mushroomFairy.png',
    description: '목공 놀잇감',
  },
  {
    id: 7,
    new: false,
    tag: 'toys',
    name: '동물인형',
    price: '13,000',
    link: 'animalDoll.png',
    description: '양모 솜을 이용한 말 인형',
  },
  {
    id: 8,
    new: false,
    tag: 'toys',
    name: '별똥별 리본',
    price: '2,500',
    link: 'shootingstarRibbon.png',
    description: '무지개 그라데이션 리본을 이용한 별똥별 리본',
  },
  {
    id: 9,
    new: false,
    tag: 'others',
    name: '침엽수 열매 (가격 미정)',
    price: '0',
    link: 'horseChestnut.png',
    description: '말린 칠엽수 열매 (가격 미정)',
  },
  {
    id: 10,
    new: false,
    tag: 'others',
    name: '동백나무 열매 (가격 미정)',
    price: '0',
    link: 'camelliaFruit.png',
    description: '말린 동백나무 열매 (가격 미정)',
  },
  {
    id: 11,
    new: false,
    tag: 'others',
    name: '마늘을 먹인 반석이네 유정란 10구',
    price: '5,000',
    link: 'garlicEggs.png',
    description: '마늘 배합사료를 먹여 키운 유정란',
  },
];

export default Items;
