const partners = [
  {
    id: 0,
    name: '강남 발도르프킨더교육원',
    email: 'ssukssuk777@hanmail.net',
    address: '서울시 강남구 논현로 22길 (아람손 B/D)',
    color: '#CCE1B0',
  },
  {
    id: 1,
    name: '강남 율현 발도르프킨더교육원',
    email: 'ssukssuk777@hanmail.net',
    address: '서울시 강남구 밤고개로 24길 54-3 (율현동)',
    color: '#CCE1B0',
  },
  {
    id: 2,
    name: '구로 항동발도르프킨더교육원',
    email: 'yonsu115@naver.com',
    address: '서울시 구로구 오리로 13길 12-6 1층 단독',
    color: '#CCE1B0',
  },
  {
    id: 3,
    name: '또래숲속발도르프킨더교육원',
    email: 'hsddor@hanmail.net',
    address: '경기도 수원시 팔달구 화서동 344-65번지',
    color: '#CCE1B0',
  },
  {
    id: 4,
    name: '사당숲속천사어린이집',
    email: 'angelkmy3383@naver.com',
    address: '서울시 동작구 사당동 300-84',
    color: '#CCE1B0',
  },
  {
    id: 5,
    name: '인천빛의아이들 킨더교육원',
    email: 'hjhhope11@naver.com',
    address: '인천광역시 남동구 장자북로 43번길 27(장수동) 금성빌딩',
    color: '#CCE1B0',
  },
  {
    id: 6,
    name: '구로수잔나어린이집',
    email: 'melo0913@hanmail.net',
    address: '서울 구로구 고척로51길 73',
    color: '#C4E6F3',
  },
  {
    id: 7,
    name: '구로큰다우리어린이집',
    email: '32813407@hanmail.net',
    address: '서울시 구로구 구로동로 28길 33-5',
    color: '#C4E6F3',
  },
  {
    id: 8,
    name: '구로항동발도르프어린이집',
    email: 'yonsu115@naver.com',
    address: '서울시 구로구 오리로 13길 12-6 1층 단독',
    color: '#C4E6F3',
  },
  {
    id: 9,
    name: '용산 꿈꾸는 어린이집',
    email: 'gtvision@hanmail.net',
    address: '서울시 용산구 효창원로 69길 57베네스A 101-104',
    color: '#C4E6F3',
  },
  {
    id: 10,
    name: '반석어린이집',
    email: 'wind-door@hanmail.net',
    address: '서울시 용산구 효창원로 178 (반석빌딩 청파3가) 2층',
    color: '#C4E6F3',
  },
  {
    id: 11,
    name: '별빛어린이집',
    email: 'guessljs@hanmail.net',
    address: '서울 용산구 이촌로 347 신동아아파트 9동 102호',
    color: '#C4E6F3',
  },
  {
    id: 12,
    name: '시흥은혜어린이집',
    email: 'yysarah@naver.com',
    address: '경기도 시흥시 신천로 19번안길 8',
    color: '#C4E6F3',
  },
  {
    id: 13,
    name: '울산희수자연학교',
    email: 'gmltnwkdus@hanmail.net',
    address: '울산시 북구 이화 4길 9 (중산동, 희수자연학교어린이집)',
    color: '#C4E6F3',
  },
  {
    id: 14,
    name: '인천사과나무어린이집',
    email: 'homeceo@hanmail.net',
    address: '인천시 계양구 도두리로 74 도두리마을 대동아파트 529동 104호',
    color: '#C4E6F3',
  },
  {
    id: 15,
    name: '일산햇빛자연발도르프어린이집',
    email: 'nayana522@hanmail.net',
    address:
      '경기도 고양시 덕양구 중앙로 558번길 57 1822동 103로 ( 행신동, 햇빛주공18단지아파트 )',
    color: '#C4E6F3',
  },
  {
    id: 16,
    name: '자연어린이집',
    email: 'chjin824@naver.com',
    address: '서울시 용산구 이촌로로 87길 14로 강촌아파트 104동 104호',
    color: '#C4E6F3',
  },
  {
    id: 17,
    name: '춘천별둥지어린이집',
    email: 'jy2ya0@naver.com',
    address: '강원도 춘천시 춘천순환로 94번길 12. 202-106',
    color: '#C4E6F3',
  },
  {
    id: 18,
    name: '춘천이루숲어린이집',
    email: 'kimyoo63@naver.com',
    address: '강원도 춘천시 백석골길 22번길 21-21',
    color: '#C4E6F3',
  },
  {
    id: 19,
    name: '춘천별숲어린이집',
    email: 'su-junga@hanmail.net',
    address: '강원도 춘천시 승지골길 16번길 47 퇴계뜨란체아파트 1007동 관리동',
    color: '#C4E6F3',
  },
  {
    id: 20,
    name: '화순낙원어린이집',
    email: 'eyo0815@hanmail.net',
    address: '전남 화순군 동면 천운길 35',
    color: '#C4E6F3',
  },
  {
    id: 21,
    name: '구립신정4동어린이집',
    email: 'keunh007@hanmail.net',
    address: '서울시 양천구 오목로 34길 5, 1층',
    color: '#E0C4E3',
  },
  {
    id: 22,
    name: '사과꽃어린이집',
    email: 'applet0469@hanmail.net',
    address: '서울시 성동구 금호로 111 금호하이리버래미안 201동 1층',
    color: '#E0C4E3',
  },
  {
    id: 23,
    name: '성동 구립 서마어린이집',
    email: 's5016@hanmail.net',
    address: '서울시 성동구 청계천로 546',
    color: '#E0C4E3',
  },
  {
    id: 24,
    name: '신촌구립 어린이집',
    email: 'p-wanmin@hanmail.net',
    address: '서울 서대문구 연세로 2 나길 48',
    color: '#E0C4E3',
  },
  {
    id: 25,
    name: '오금숲 어린이집',
    email: 'jay0903@hanmail.net',
    address: '서울시 송파구 오금동 47-6',
    color: '#E0C4E3',
  },
  {
    id: 26,
    name: '인천서구청 어린이집',
    email: 'jbchcho@hanmail.net',
    address: '인천광역시 서구 승학로 264',
    color: '#E0C4E3',
  },
  {
    id: 27,
    name: '춘천후평우미린어린이집',
    email: 'gsesther@hanmail.net',
    address: '강원도 춘천시 보안길36, 후평우미린뉴시티 관리동',
    color: '#E0C4E3',
  },
  {
    id: 28,
    name: '강서 햇빛발도르프어린이집',
    email: 'ckbsoh@hanmail.net',
    address: '서울시 강서구 까치산로 18길 35',
    color: '#FBDED4',
  },
  {
    id: 29,
    name: '바람아래 어린이집',
    email: 'haselnuss@hanmail.net',
    address: '서울 성북구 길음로 9길 40 길음래미안 1차 108동 101호',
    color: '#FBDED4',
  },
  {
    id: 30,
    name: '별꽃씨어린이집',
    email: 'babysesang@nate.com',
    address: '경기도 용인시 수지구 동천로 178번길 24-2번지',
    color: '#FBDED4',
  },
  {
    id: 31,
    name: '부산메이플유치원',
    email: 'sun2233@hanmail.net',
    address: '부산광역시 사하구 다대로 620',
    color: '#99CEC7',
  },
  {
    id: 32,
    name: '이화유치원',
    email: 'choina@unitel.co.kr',
    address: '서울시 강서구 방화동 449-27',
    color: '#99CEC7',
  },
];

export default partners;
